package entities;

// Generated 15 ao�t 2018 16:23:18 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Applications generated by hbm2java
 */
@Entity
@Table(name = "applications", catalog = "db", uniqueConstraints = @UniqueConstraint(
    columnNames = "name"))
public class Applications implements java.io.Serializable {

  private Integer id;
  private String name;
  private String label;
  private Set<Menus> menuses = new HashSet<Menus>(0);

  public Applications() {}

  public Applications(String name, String label, Set<Menus> menuses) {
    this.name = name;
    this.label = label;
    this.menuses = menuses;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @Column(name = "name", unique = true, length = 180)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "label", length = 1024)
  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "applications")
  public Set<Menus> getMenuses() {
    return this.menuses;
  }

  public void setMenuses(Set<Menus> menuses) {
    this.menuses = menuses;
  }

}
