package entities;

// Generated by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "db", uniqueConstraints = {
    @UniqueConstraint(columnNames = "fatherid"), @UniqueConstraint(columnNames = "name")})
public class Menu implements java.io.Serializable {

  private Integer id;
  private Application application;
  private Menu menu;
  private String name;
  private String label;
  private Set<Menu> menuses = new HashSet<Menu>(0);

  public Menu() {}

  public Menu(Application application, String name, String label) {
    this.application = application;
    this.name = name;
    this.label = label;
  }

  public Menu(Application application, Menu menu, String name, String label, Set<Menu> menuses) {
    this.application = application;
    this.menu = menu;
    this.name = name;
    this.label = label;
    this.menuses = menuses;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "applicationid", nullable = false)
  public Application getApplication() {
    return this.application;
  }

  public void setApplication(Application application) {
    this.application = application;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fatherid", unique = true)
  public Menu getMenu() {
    return this.menu;
  }

  public void setMenu(Menu menu) {
    this.menu = menu;
  }

  @Column(name = "name", unique = true, nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "label", nullable = false, length = 250)
  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
  public Set<Menu> getMenuses() {
    return this.menuses;
  }

  public void setMenuses(Set<Menu> menuses) {
    this.menuses = menuses;
  }

}
