package entities;

// Generated by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Menus generated by hbm2java
 */
@Entity
@Table(name = "menus", catalog = "db", uniqueConstraints = {
    @UniqueConstraint(columnNames = "fatherid"), @UniqueConstraint(columnNames = "name")})
public class Menus implements java.io.Serializable {

  private Integer id;
  private Applications applications;
  private Menus menus;
  private String name;
  private String label;
  private Set<Menus> menuses = new HashSet<Menus>(0);

  public Menus() {}

  public Menus(Applications applications, String name, String label) {
    this.applications = applications;
    this.name = name;
    this.label = label;
  }

  public Menus(Applications applications, Menus menus, String name, String label, Set<Menus> menuses) {
    this.applications = applications;
    this.menus = menus;
    this.name = name;
    this.label = label;
    this.menuses = menuses;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "applicationid", nullable = false)
  public Applications getApplications() {
    return this.applications;
  }

  public void setApplications(Applications applications) {
    this.applications = applications;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fatherid", unique = true)
  public Menus getMenus() {
    return this.menus;
  }

  public void setMenus(Menus menus) {
    this.menus = menus;
  }

  @Column(name = "name", unique = true, nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "label", nullable = false, length = 250)
  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "menus")
  public Set<Menus> getMenuses() {
    return this.menuses;
  }

  public void setMenuses(Set<Menus> menuses) {
    this.menuses = menuses;
  }

}
